modificaiton of update script to be ran on a host system

diff --git a/tkgl_bootstrap_[ProjectData]/scripts/tkgl_bootstrap b/tkgl_bootstrap_[ProjectData]/scripts/tkgl_bootstrap
--- a/tkgl_bootstrap_[ProjectData]/scripts/tkgl_bootstrap
+++ b/tkgl_bootstrap_[ProjectData]/scripts/tkgl_bootstrap
@@ -6,63 +6,127 @@
 #   _|  _| |_|\___| _|\_\_|_|\_\\____|\___|_|  _| _____|\__,_|_.__/ ____/
 #
 # BOOTSTRAP script for MPC device.
-# POST AZ01-LAUNCH-MPC script
+# Bootstrap autoupdate from the github repository
+#------------------------------------------------------------------------------
+# Update can be done manually with the following command :
+#
+#  ssh root@192.168.2.25 "sh /media/TKGL_BOOTSTRAP/tkgl_bootstrap_[ProjectData]/scripts/tkgl_update"
+
 
 SCRIPT_NAME=$(readlink -f "$0")
 SCRIPT_DIR=$(dirname "$SCRIPT_NAME")
-source "$SCRIPT_DIR/tkgl_path"
 
-# -----------------------------------------------------------------------------
-# Read the doer_list at the tkgl_root dir
+# TKGL_ Context variables
+MOUNT_POINT="$SCRIPT_DIR/../.."
+TKGL_BIN="$SCRIPT_DIR/../bin"
+DOER_LIST="$SCRIPT_DIR/../doer_list"
 
-[ -f "$TKGL_ROOT/doer_list" ] || exit 1
+UPDATE_DIR=$SCRIPT_DIR/update
+UPDATE_URL="https://github.com/TheKikGen/MPC-LiveXplore-bootstrap/archive/refs/heads/main.zip"
+UPDATE_PACK_FILE=$SCRIPT_DIR/bootstrap-update.zip
 
-cat "$TKGL_ROOT/doer_list">>$TKGL_LOG
-source "$TKGL_ROOT/doer_list"
+#IamForce2 assets download
+IAMFORCE_ROOTFS_IMG_GOOGLE_ID="15cWYw1HbnDBlseqmlPB4_l7IqChBX27I"
+IAMFORCE_ROOTFS_IMG_FILE_NAME="$SCRIPT_DIR/../modules/mod_iamforce2/force-assets/rootfs_force-3.2.3.3-update.img"
 
-# -----------------------------------------------------------------------------
+# Script starts here
 
-# for debugging purpose locally:
-if [ "x$TKGL_PATH_FILE" == "x" ]
-then
-  export TKGL_PATH_FILE=$(dirname $(readlink -f "$0"))/tkgl_path
+echo " _____ _          _  ___ _                   _         _       "
+echo "|_   _| |_  ___  | |/ (_| |____ _ ___ _ _   | |   __ _| |__ ___"
+echo "  | | |   \/ -_) |   <| | / / _  / -_|   \  | |__/ _  |  _ (_-< "
+echo "  |_| |_||_\___| |_|\_|_|_\_\__, \___|_||_| |____\__,_|_.__/__/ "
+echo "                            |___/                               "
+echo ""
+echo "TKGL BOOTSTRAP UPDATE SCRIPT"
+echo "----------------------------------------------------------------------------------------"
+echo "" 
+read -p "Are you really sure you to update the bootstrap (Y/N) ? " answer
+if [ "$answer" != "${answer#[Yy]}" ] ;then 
+    echo "Proceeding update...."
+else
+    echo "Update aborted."
+    exit 0
 fi
 
-source $TKGL_PATH_FILE
+[ "$1" = "system" ] && TKGL_BIN=usr/bin
 
-echo "-------------------------------------------------------------------------">$TKGL_LOG
-echo " TKGL_BOOTSTARP SCRIPT : $TKGL_BOOTSTRAP" >> $TKGL_LOG
-date >> $TKGL_LOG
-uname -a >> $TKGL_LOG
-echo >> $TKGL_LOG
+# Check TKGL environment. We need curl...
+if [ ! -f "$TKGL_BIN/curl" ]; then
+  echo "Error : $TKGL_BIN/curl is missing. Can't proceed with the bootstrap update."
+  echo "If not running on the MPC, you can use "tkgl_update system" to use the curl system binary."
+  echo "In that case, the sytem will not reboot".
+  exit 1
+fi
 
-for MODULE in $TKGL_DOER ; do
-  
-   # Check if a parameter exists in the module name.  Form is <module name>@<parameter value>
+# Clean function
+clean () {
+  [ -f "$UPDATE_PACK_FILE" ] && rm $UPDATE_PACK_FILE
+  [ -d "$UPDATE_DIR" ] && rm -rf $UPDATE_DIR
+  [ -f "$UPDATE_FLAG_FILE" ] && rm $UPDATE_FLAG_FILE
+  [ -f "$DOER_LIST.bak" ] && rm $DOER_LIST.bak
+}
 
-   MODULE_PRM=$(echo $MODULE | cut -d@ -f2 )
-   MODULE_NAME=$(echo $MODULE | cut -d@ -f1 )
+echo ">> Stop MPC application..."
 
-   echo  >> $TKGL_LOG
-   echo "-------------------------------------------------------------------------">>$TKGL_LOG
-   echo "-- Module $MODULE_NAME ($MODULE_PRM) --">>$TKGL_LOG
-   echo "-------------------------------------------------------------------------">>$TKGL_LOG
-   _MODULE_LAUNCH_SCRIPT="$TKGL_ROOT/modules/mod_$MODULE_NAME/tkgl_mod_$MODULE_NAME.sh"
-   
-   if [ -f "$_MODULE_LAUNCH_SCRIPT" ]
-   then
-      echo "Launch script $_MODULE_LAUNCH_SCRIPT found.">>$TKGL_LOG
-      PRMS=""
-      SAV_IFS=$IFS
-      IFS=","
-      for p in $MODULE_PRM ; do
-         PRMS="$PRMS ${p}"
-      done
-      IFS=$SAV_IFS
-      echo "Parsed parameters : $PRMS">>$TKGL_LOG
-      sh "$TKGL_ROOT/modules/mod_$MODULE_NAME/tkgl_mod_$MODULE_NAME.sh" $PRMS
-   else
-      echo "*** Error : launch script $_MODULE_LAUNCH_SCRIPT not found">>$TKGL_LOG
-   fi
+# stop MPC application
+systemctl stop inmusic-mpc
 
-done
+clean
+
+# Make a backup of doer_list
+cp $DOER_LIST $DOER_LIST.bak 
+
+# temp directory for downloads
+mkdir -p $UPDATE_DIR
+
+echo ">> Downloading update from Github, please wait..."
+
+$TKGL_BIN/curl -L $UPDATE_URL --output $UPDATE_PACK_FILE
+if [ $? -ne 0 ]; then
+  echo "Curl error while attempting to download update package at $UPDATE_URL"
+  clean
+  exit 1
+fi
+
+echo ">> Decompressing files. Please wait..."
+
+unzip $UPDATE_PACK_FILE -d $UPDATE_DIR
+if [ $? -ne 0 ]; then
+  echo "Error while attempting to unzip package file $UPDATE_PACK_FILE"
+  clean
+  exit 1
+fi
+
+echo ">> Copying files to the bootstrap directories. Please wait..."
+
+cp -a "$UPDATE_DIR/MPC-LiveXplore-bootstrap-main/tkgl_bootstrap_[ProjectData]" "$MOUNT_POINT/"
+if [ $? -ne 0 ]; then
+  echo "Error while copying bootstrap update files"
+  #clean
+  exit 1
+fi
+
+#ls -l -R "$UPDATE_DIR/MPC-LiveXplore-bootstrap-main"/*
+
+# Restore the doer_list file
+cp $DOER_LIST.bak $DOER_LIST 
+if [ $? -ne 0 ]; then
+  echo "Error while restoring bootstrap $DOER_LIST file. The process will continue."
+fi
+
+clean
+
+echo ""
+
+if [ ! -f $IAMFORCE_ROOTFS_IMG_FILE_NAME ]; then
+  echo ">> IamForce2 assets download from Google drive..."
+  $TKGL_BIN/curl -o $IAMFORCE_ROOTFS_IMG_FILE_NAME -L "https://drive.google.com/uc?export=download&confirm=yes&id=$IAMFORCE_ROOTFS_IMG_GOOGLE_ID"
+else
+  echo "IamForce2 assets $IAMFORCE_ROOTFS_IMG_FILE_NAME already on smartcard."
+fi
+echo ""
+echo ""
+echo "Update finished correctly. Rebooting MPC..."
+echo "May the IamForce be with you !"
+
+[ "$1" != "system" ] && reboot
